### ISSUE TITLE
Calculate the % of the difference between Matadata and text

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-content-integrity#15]

**Comment by MaNe2020** [comment]
@ggrig @chrisdiao there is no info about how to verify this and what work has been done. 
Along with no description for the issue. Pls add more details.

**Comment by ggrig** [comment]
To verify the functionality, follow the steps below:

1. git clone https://github.com/filetrust/cdr-content-integrity
2. cd ./cdr-content-integrity
3. sudo docker-compose up
 This starts cdr_content_extraction and Tika server locally
4. cp .env.sample .env
You may consider changing the settings in .env to run the comparison for other cdr-plugin-folder-to-folder scenarios. 
In my case it looks as following:
![image](https://user-images.githubusercontent.com/26714598/122538166-530be800-d037-11eb-9a24-f985d9e04457.png)
5. cdr-content-integrity> python3 .\cdr_content_management\comparison\Compare_Texts.py
The command will try comparing metadata and text of files from HD2 and HD3 create comparison reports within corresponding HD2 metadata folders:
![image](https://user-images.githubusercontent.com/26714598/122538412-8fd7df00-d037-11eb-812a-7d29b3c9b7b0.png)
6. See % in comparison_report.json
![image](https://user-images.githubusercontent.com/26714598/122538626-ce6d9980-d037-11eb-84b6-d044dc4b0902.png)
7. Verify the numbers with text comparison tool (one like codecompare) applied to pairs 
left_metadata & right_metadata
left_text & right_text

**Comment by chrisdiao** [comment]
@MaNe2020 , could you please check this again and verify, please.

**Comment by MaNe2020** [comment]
@ggrig I tried as per your steps (both on linux and win) and I am getting 
![image](https://user-images.githubusercontent.com/70108899/122685744-961fb400-d20d-11eb-8b27-7f30a06da22c.png)

Also tried to run it from pyCharm, there I am getting this
![image](https://user-images.githubusercontent.com/70108899/122685760-acc60b00-d20d-11eb-9457-c274ef25021e.png)

Do you know how I can fix this?

This is my .env
![image](https://user-images.githubusercontent.com/70108899/122685776-c404f880-d20d-11eb-9ca0-ee66067a3727.png)

**Comment by chrisdiao** [comment]
Hello @gmuditdce @ggrig , could you please check @MaNe2020 inquiry please?

**Comment by gmuditdce** [comment]
@MaNe2020 please try adding cdr_content_management as sources root in Pycharm (module dependencies are resolved)
It gives issues with python command line which may need fix, works with pycharm, let us try with it till
@ggrig we should consider converting text comparison to docker
![image](https://user-images.githubusercontent.com/71660612/122942569-ee80be00-d393-11eb-9dbe-ee0ec8b6a279.png)

**Comment by ggrig** [comment]
I have it in PYTHONPATH on both Windows and Linux
![image](https://user-images.githubusercontent.com/26714598/122957370-ed9b5c80-d392-11eb-91db-30ce22f3b4d4.png)

**Comment by MaNe2020** [comment]
I am still not able to verify this as I am getting `TypeError: '_NamespacePath' object does not support indexing`
@chrisdiao but since both @gmuditdce and @ggrig verified this and we will have work that continues on this, will move it for release. 

Created another issue for continuing work on this one: https://github.com/filetrust/cdr-content-integrity/issues/53

**Comment by chrisdiao** [comment]
This is included in v0.1.0 release
